name: fasum
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  path: ^1.9.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  geolocator: ^14.0.0
  flutter_image_compress: ^2.4.0
  url_launcher: ^6.3.1
  google_generative_ai: ^0.4.7
  shimmer: ^3.0.0
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
